version: '3'
services:
  ros:
    build: .
    command: tail -f /dev/null
    volumes: 
      - ./user01:/home/user01
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
  novnc:  
    image: theasp/novnc:latest
    env_file:
      - novnc.env
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
